---

- name: install mailutils
  package: name=mailutils state=present
  async: 120
  poll: 10
  when: ansible_os_family == "Debian" and not ansible_check_mode

- name: check that mailutils is installed
  package: name=mailutils state=present
  when: ansible_os_family == "Debian" and ansible_check_mode

- name: install mailx
  package: name=mailx state=present
  when: ansible_os_family == "RedHat"

- name: install fail2ban
  package: name=fail2ban state=present

- name: make fail2ban persistent
  service: name=fail2ban enabled=yes state=started

- name: install iptables-persistent
  package: name=iptables-persistent state=present

- name: make sure netfilter-persistent is enabled
  service: name=netfilter-persistent enabled=yes state=started

- name: push specific fail2ban configuration files
  template: src={{ item }}.{{ ansible_distribution }}{{ ansible_distribution_major_version }}.j2 dest=/etc/fail2ban/{{ item }}.local
  with_items:
    - jail
    - action.d/mail-whois
    - action.d/mail-whois-lines
  when: ansible_os_family == "Debian"
  notify: restart fail2ban

- name: create iptables configuration
  template: src=iptables.conf.j2 dest=/etc/iptables/rules.v4 owner=root group=root mode=0600
  notify: 
    - restore-iptables
    - restart fail2ban
    - restart docker
