---

## Install Nagios docker
- name: create Nagios docker structure on server in {{ docker_location }}odoo
  file:
    name: "{{ item }}"
    state: directory
    owner: 999
    group: 1000
  with_items:
  - "{{ docker_location }}nagios/custom"
  - "{{ docker_location }}nagios/etc/objects"
  - "{{ docker_location }}nagios/stylesheets"

- name: Install nagios docker
  template:
    src: nagios.yaml.j2
    dest: "{{ docker_location }}nagios/nagios.yaml"
    owner: root
    group: root
    mode: 0644 
  notify: restart nagios docker

- name: get ssl certificate verification module from github
  get_url:
    url: https://raw.githubusercontent.com/matteocorti/check_ssl_cert/v1.56.0/check_ssl_cert
    dest: "{{ docker_location }}nagios/custom/check_ssl_cert"
    mode: 0555
  notify: restart nagios docker
  tags: nagios_config

- name: copy configuration files
  copy:
    src: "{{ item }}"
    dest: "{{ docker_location }}nagios/etc/{{ item }}"
    mode: 0644
    owner: 999
    group: 1000
  with_items:
    - cgi.cfg
    - nagios.cfg
    - resource.cfg
  notify: restart nagios docker
  tags: nagios_config

- name: copy htpasswd configuration file
  copy:
    src: roles/nagios/files/htpasswd.users
    dest: "{{ docker_location }}nagios/etc/htpasswd.users"
    mode: 0644
    owner: root
    group: root
  notify: restart nagios docker
  tags: nagios_config

- name: copy CSS files
  copy:
    src: "roles/nagios/files/{{ item }}"
    dest: "{{ docker_location }}nagios/stylesheets/{{ item }}"
    mode: 0644
    owner: 999
    group: 1000
  with_items:
    - avail.css
    - checksanity.css
    - cmd.css
    - common.css
    - config.css
    - extinfo.css
    - histogram.css
    - histogramgraph.css
    - history.css
    - jsonquery.css
    - map.css
    - map-directive.css
    - ministatus.css
    - nag_funcs.css
    - notifications.css
    - outages.css
    - showlog.css
    - status.css
    - statusmap.css
    - summary.css
    - tac.css
    - trends.css
    - trendsgraph.css
  notify: restart nagios docker
  tags: nagios_config

- name: install objects configuration files
  template:
    src: "{{ item }}.j2"
    dest: "{{ docker_location }}nagios/etc/objects/{{ item }}"
    mode: 0644
    owner: 999
    group: 1000
  with_items:
    - vps.cfg
    - localhost.cfg
    - templates.cfg
    - contacts.cfg
    - commands.cfg
    - windows.cfg
    - timeperiods.cfg
  notify: restart nagios docker
  tags: nagios_config

- name: start nagios docker
  docker_service:
    project_src: "{{ docker_location }}nagios/"
    files: nagios.yaml
  tags: start_docker

