---

- name: install dependencies packages and PostgreSQL
  apt:  
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - gcc
    - python-dev
    - postgresql
    - postgresql-server-dev-all
    - python-setuptools
    - nginx
    - letsencrypt
    - php7.0-fpm
    - php7.0-xml
    - php7.0-zip
    - php7.0-pgsql
    - php7.0-gd 
    - php7.0-mbstring 
    - php7.0-curl

- name: Install tool packages easyInstall
  easy_install: 
    name: "{{ item }}"
  with_items:
    - psycopg2

- name: Creating the Owncloud PostgreSQL User
  postgresql_user: 
    name: owncloud 
    role_attr_flags: "CREATEDB,NOSUPERUSER,LOGIN"
    password: "{{ cloud_pg_hash }}"
  become: yes
  become_user: postgres

- name: Creating the Owncloud PostgreSQL DB
  postgresql_db: 
    name: owncloud
    owner: owncloud
  become: yes
  become_user: postgres

- name: download and install Owncloud
  unarchive:
    src: https://download.owncloud.org/community/owncloud-10.0.4.tar.bz2
    remote_src: yes
    dest: /var/www/

- name: generate certificate
  command: letsencrypt certonly -a webroot --webroot-path=/var/www/html -d {{ cloud_url }} -n --agree-tos --email {{ maintenance_email }}

- name: add cron job to renew certificate every monday
  cron:
    name: renew certificate
    minute: 30
    hour: 2
    weekday: 1
    job: /usr/bin/letsencrypt renew >> /var/log/le-renew.log && service nginx reload

- name: add cron job to restart proxy following certificate renewal
  cron:
    name: reload proxy
    minute: 40
    hour: 2
    weekday: 1
    job: service nginx reload
    state: absent

#--------------------------------------------------
# NGINX Configuration
#--------------------------------------------------

- name: Configure Nginx
  template: src=owncloud.j2 dest="/etc/nginx/sites-available/owncloud"
  notify: restart nginx

- name: "Enable nginx configuration"
  file: src="/etc/nginx/sites-available/owncloud" dest="/etc/nginx/sites-enabled/owncloud" state=link
  notify: restart nginx

- name: Remove default Nginx configuration
  file: path="/etc/nginx/sites-enabled/default" state=absent
  notify: restart nginx


#--------------------------------------------------
# Permissions
#--------------------------------------------------
- name: Set file rights on the ones to be owned by root
  file:
    path: "{{ item }}"
    owner: root
    group: www-data
    mode: g-w,o-rwx
    recurse: yes
    state: directory
  with_items:
  - /var/www/owncloud/
  tags: owncloud_permissions

- name: Set file rights on the ones to be owned by htuser
  file:
    path: "{{ item }}"
    owner: www-data
    group: www-data
    mode: g-w,o-rwx
    recurse: yes
    state: directory
  with_items:
  - /var/www/owncloud/apps
  - /var/www/owncloud/config
  - /var/www/owncloud/updater
  - "{{ cloud_data_dir }}/"
  tags: owncloud_permissions

- name: Set execution right on occ 
  file:
    path: "{{ item }}"
    owner: www-data
    group: www-data
    mode: +x
  with_items:
  - /var/www/owncloud/occ
  tags: owncloud_permissions

- name: Limit rights on htaccess 
  file:
    path: "{{ item }}"
    owner: root
    group: www-data
    mode: 0644
  with_items:
  - /var/www/owncloud/.htaccess
  - "{{ cloud_data_dir }}/.htaccess"
  ignore_errors: yes
  tags: owncloud_permissions
